UNDataForum/gatsby-themes

- themes/gatsby-theme-events/src/components/event-page.js
> Fix prop-type in EventPage

- .changeset/rare-games-switch.md
- site/src/@undataforum/gatsby-theme-base/components/footer.js
> Update shadowed footer to new components API

- .changeset/beige-sheep-thank.md
- themes/gatsby-theme-events/gatsby/source-nodes.js
> Add registration prop to GraphQL Event type

- .changeset/tender-buckets-pay.md
- themes/gatsby-theme-base/package.json
- themes/gatsby-theme-blog/package.json
- themes/gatsby-theme-events/package.json
- themes/gatsby-theme-profiles/package.json
> Fix invalid repository prop in package.json files

- .changeset/few-pans-carry.md
- .changeset/warm-tools-wait.md
- themes/gatsby-theme-blog/src/components/posts-page.js
- themes/gatsby-theme-blog/src/templates/posts.js
> New layout for blog page

- .changeset/fast-fireants-fold.md
- themes/gatsby-theme-blog/src/components/posts-page.js
- themes/gatsby-theme-events/src/components/events-page.js
> Display events with grid on events page

- .changeset/thick-rockets-smash.md
- themes/gatsby-theme-events/src/templates/event.js
- themes/gatsby-theme-events/src/templates/events.js
- yarn.lock
> Use Names to display speakers on events page

- .changeset/wet-guests-report.md
- site/src/@undataforum/gatsby-theme-base/components/header.js
> Remove height prop from shadowed Header

- .changeset/chatty-carrots-search.md
- .changeset/little-hounds-admire.md
- .changeset/silent-baboons-buy.md
- themes/gatsby-theme-base/package.json
- themes/gatsby-theme-base/src/gatsby-plugin-theme-ui/index.js
- themes/gatsby-theme-events/gatsby/on-create-node.js
- themes/gatsby-theme-events/package.json
- themes/gatsby-theme-events/src/components/event-page.js
- themes/gatsby-theme-events/src/components/events-page.js
- themes/gatsby-theme-events/src/templates/event.js
- themes/gatsby-theme-events/src/templates/events.js
- yarn.lock
> Improve layout of events

- .changeset/brown-impalas-kiss.md
- themes/gatsby-theme-profiles/package.json
- themes/gatsby-theme-profiles/src/components/profiles-page.js
- yarn.lock
> Display profiles with multi-column grid

- .changeset/sweet-pumas-appear.md
- themes/gatsby-theme-blog/gatsby-config.js
- themes/gatsby-theme-blog/gatsby/on-create-node.js
- themes/gatsby-theme-events/gatsby-config.js
- themes/gatsby-theme-events/gatsby/on-create-node.js
- themes/gatsby-theme-profiles/gatsby-config.js
- themes/gatsby-theme-profiles/gatsby/on-create-node.js
> Fix processing of path in onCreateNode

- .changeset/light-baboons-tan.md
- site/content/profiles/cleric-edis.md
- site/content/profiles/nance-mcfadin.md
- site/content/profiles/sandra-abramovici-floris.md
- themes/gatsby-theme-profiles/gatsby/on-create-node.js
- themes/gatsby-theme-profiles/gatsby/source-nodes.js
- themes/gatsby-theme-profiles/index.js
- themes/gatsby-theme-profiles/src/components/profiles-page.js
- themes/gatsby-theme-profiles/src/templates/profile.js
- themes/gatsby-theme-profiles/src/templates/profiles.js
> Add roles to profiles

- .changeset/wise-laws-build.md
- site/package.json
- yarn.lock
> Disable Gatsby telemetry

- .changeset/gentle-ties-listen.md
- .changeset/soft-planes-study.md
- site/package.json
- site/src/@undataforum/gatsby-theme-base/components/layout.js
- site/src/gatsby-plugin-theme-ui/index.js
- themes/gatsby-theme-base/src/gatsby-plugin-theme-ui/index.js
- yarn.lock
> Make custom font work

- .changeset/quick-socks-smell.md
- themes/gatsby-theme-profiles/src/components/profiles-page.js
> Increase grid gap in profiles page

- .changeset/strange-teachers-develop.md
- site/gatsby-config.js
- site/src/pages/index.js
> Fix missing title in homepage

- .changeset/tall-shoes-flow.md
- themes/gatsby-theme-profiles/package.json
> Fix repo URL in package.json

- .prettierrc
> Configure proseWrap for Prettier

- .changeset/shaggy-planes-live.md
- themes/gatsby-theme-base/src/pages/contact.md
> Put note in contact page about shadowing

- .changeset/plenty-years-punch.md
- site/content/events/multiple-paras-with-import.md
- site/content/events/multiple-paras-without-import.md
- themes/gatsby-theme-events/gatsby/on-create-node.js
- themes/gatsby-theme-events/src/templates/events.js
> Fix sort order on events page

- .changeset/nasty-feet-play.md
- .changeset/nervous-dogs-melt.md
- site/content/posts/eaque-ipsa-quae.md
- site/content/posts/et-harum-quidem-rerum.md
- site/content/posts/gatsby-remark-smartypants.md
- site/content/posts/inventore-veritatis.md
- site/content/posts/quia-consequuntur-magni.md
- site/content/posts/sed-ut-perspiciatis.md
- site/content/profiles/cleric-edis.md
- site/content/profiles/clifford-skipperbottom.md
- site/content/profiles/nance-mcfadin.md
- site/content/profiles/sandra-abramovici-floris.md
- site/content/profiles/suzy-cahan.md
- themes/gatsby-theme-blog/gatsby/on-create-node.js
- themes/gatsby-theme-blog/package.json
- themes/gatsby-theme-profiles/gatsby/on-create-node.js
- themes/gatsby-theme-profiles/package.json
- yarn.lock
> Fix regex for descriptions in posts and profiles

- .changeset/two-turtles-ring.md
- site/content/events/multiple-paras-with-import.md
- site/content/posts/quia-consequuntur-magni.md
- themes/gatsby-theme-blog/gatsby/on-create-node.js
- themes/gatsby-theme-events/gatsby/on-create-node.js
> Remove line feeds from description text

- .changeset/forty-forks-punch.md
- site/src/pages/index.js
- themes/gatsby-theme-base/src/components/layout.js
> Restore normal header on homepage

- site/src/components/experience.js
- site/src/pages/index.js
> Add Experience component prototype

- site/src/components/about.js
- site/src/pages/index.js
> Add About component prototype

- site/src/components/experience.js
- site/src/gatsby-plugin-theme-ui/index.js
> Use color boxes for Experience component

- .changeset/metal-toys-cheat.md
- site/content/events/multiple-paras-with-import.md
- site/content/events/one-para-with-import.md
- site/content/posts/quia-consequuntur-magni.md
- site/package.json
- themes/gatsby-theme-base/package.json
- themes/gatsby-theme-base/src/gatsby-plugin-theme-ui/index.js
- themes/gatsby-theme-blog/package.json
- themes/gatsby-theme-events/package.json
- themes/gatsby-theme-events/src/components/event-page.js
- themes/gatsby-theme-profiles/package.json
- themes/gatsby-theme-profiles/src/templates/profile.js
- yarn.lock
> Add theme-ui to peerDependencies

- .changeset/tame-waves-flash.md
- themes/gatsby-theme-base/package.json
> Add missing peer dependency @emotion/core

- .changeset/proud-students-marry.md
- themes/gatsby-theme-events/src/templates/events.js
> Add mb after tag in EventPreview via render prop

- .changeset/cyan-cherries-joke.md
- themes/gatsby-theme-base/src/components/seo.js
> Fix og:title meta tag in Seo component

- site/package.json
> Disable telemetry for yarn run clean

- .changeset/tasty-pens-live.md
- site/src/pages/test.md
- themes/gatsby-theme-base/src/gatsby-plugin-theme-ui/index.js
> Use NewTabLink for external links

- .changeset/pink-parents-jam.md
- themes/gatsby-theme-base/src/components/seo.js
> Fix twitter:title meta tag in Seo component

- site/content/events/one-para-with-import.md
- site/src/components/experience.js
- site/src/components/hero.js
- site/src/pages/index.js
> Redesign homepage

- renovate.json
> Config Renovate Bot to do less frequent updates

- renovate.json
> Group Theme UI packages in Renovate Bot pull requests

- .github/workflows/release.yml
- package.json
> Release packages to NPM with a GitHub action

- themes/gatsby-theme-base/gatsby-config.js
- themes/gatsby-theme-base/package.json
- themes/gatsby-theme-blog/gatsby-config.js
- themes/gatsby-theme-blog/package.json
- themes/gatsby-theme-events/gatsby-config.js
- themes/gatsby-theme-events/package.json
- themes/gatsby-theme-profiles/gatsby-config.js
- themes/gatsby-theme-profiles/package.json
- yarn.lock
> Remove gatsby-plugin-compile-es6-packages

- .changeset/lemon-geckos-own.md
- microfrontends/profiles/src/@undataforum/gatsby-theme-profiles/i18n/translations/en.js
- site/package.json
- themes/gatsby-theme-profiles/README.md
- themes/gatsby-theme-profiles/gatsby-node.js
- themes/gatsby-theme-profiles/package.json
- themes/gatsby-theme-profiles/src/components/profiles.js
- themes/gatsby-theme-profiles/src/i18n/messages.js
- themes/gatsby-theme-profiles/src/i18n/translations/en.js
- yarn.lock
> Localize title and description of profiles overview page

- microfrontends/blog/content/posts/et-harum-quidem-rerum.mdx
- package.json
> Change file ending of MDX file to .mdx

- .changeset/good-lobsters-accept.md
- .changeset/nice-terms-shave.md
- themes/gatsby-theme-base/LICENSE
- themes/gatsby-theme-base/src/pages/copyright.md
- themes/gatsby-theme-blog/LICENSE
- themes/gatsby-theme-events/LICENSE
- themes/gatsby-theme-profiles/LICENSE
> Update copyright to 2020

- .changeset/happy-trains-thank.md
- themes/gatsby-theme-base/package.json
- yarn.lock
> Fix links not rendering properly in Markdown pages

- .changeset/quick-cheetahs-call.md
- microfrontends/blog/content/posts/eaque-ipsa-quae.md
- microfrontends/blog/content/posts/et-harum-quidem-rerum.mdx
- microfrontends/blog/content/posts/gatsby-remark-smartypants.md
- microfrontends/blog/content/posts/inventore-veritatis.md
- microfrontends/blog/content/posts/quia-consequuntur-magni.md
- microfrontends/blog/content/posts/sed-ut-perspiciatis.md
- themes/gatsby-theme-blog/package.json
- themes/gatsby-theme-blog/src/components/post.js
- themes/gatsby-theme-blog/src/components/posts.js
- themes/gatsby-theme-events/src/components/events.js
- yarn.lock
> Fix header sizes on posts page

- .changeset/quick-wombats-doubt.md
- themes/gatsby-theme-events/package.json
- themes/gatsby-theme-events/src/components/events.js
- yarn.lock
> Change event headings to h2 in events overview page

- lint-staged.config.js
> Add support for .mdx files in project configs

- .changeset/real-berries-poke.md
- themes/gatsby-theme-events/src/templates/event-query.js
- themes/gatsby-theme-events/src/templates/events-query.js
> Remove unnecessary props from GraphQL queries

- .changeset/famous-avocados-mix.md
- .changeset/loud-rules-judge.md
- .changeset/orange-mails-lick.md
- microfrontends/webinars/content/webinars/multiple-paras-with-import.mdx
- microfrontends/webinars/content/webinars/multiple-paras-without-import.md
- microfrontends/webinars/content/webinars/one-para-with-import.mdx
- microfrontends/webinars/content/webinars/one-para-without-import.md
- microfrontends/webinars/src/@undataforum/gatsby-theme-events/templates/events-query.js
- themes/gatsby-theme-blog/package.json
- themes/gatsby-theme-blog/src/components/post-page.js
- themes/gatsby-theme-blog/src/components/posts-page.js
- themes/gatsby-theme-blog/src/templates/post-query.js
- themes/gatsby-theme-events/package.json
- themes/gatsby-theme-events/src/components/event-page.js
- themes/gatsby-theme-events/src/components/events-page.js
- themes/gatsby-theme-events/src/templates/event-query.js
- themes/gatsby-theme-events/utils/decorate-moderators.js
- yarn.lock
> Make description prop optional in events overview page

- .changeset/dull-coats-accept.md
- themes/gatsby-theme-base/package.json
- themes/gatsby-theme-base/src/components/logo.js
- yarn.lock
> Remove dependency non-existing legacy prop-type

- .changeset/khaki-timers-tap.md
- themes/gatsby-theme-blog/gatsby-node.js
- themes/gatsby-theme-events/gatsby-node.js
> Fix node types of title and description nodes

- .changeset/gold-nails-punch.md
- themes/gatsby-theme-base/package.json
- themes/gatsby-theme-base/src/components/layout.js
- yarn.lock
> Pass ...props to Header in Layout

- .changeset/brown-toys-join.md
- site/package.json
- themes/gatsby-theme-blog/README.md
- themes/gatsby-theme-blog/gatsby-node.js
- themes/gatsby-theme-blog/package.json
- themes/gatsby-theme-events/README.md
- themes/gatsby-theme-events/gatsby-node.js
- themes/gatsby-theme-events/package.json
- themes/gatsby-theme-events/src/components/event-page.js
- themes/gatsby-theme-events/src/components/events-page.js
- yarn.lock
> Add missing fields to GraphQL types

- .changeset/breezy-rivers-wonder.md
- site/package.json
- themes/gatsby-theme-base/package.json
- yarn.lock
> Fix theme-ui render problem related to gatsby-plugin-mdx

- .changeset/sour-phones-sip.md
- microfrontends/webinars/content/webinars/multiple-paras-with-import.mdx
- microfrontends/webinars/content/webinars/multiple-paras-without-import.md
- microfrontends/webinars/content/webinars/one-para-with-import.mdx
- microfrontends/webinars/content/webinars/one-para-without-import.md
> Rename `zone` to `timezone` in events frontmatter

- renovate.json
> Turn off semantic commits in renovate.json

- .github/workflows/code-qa.yml
- .github/workflows/release.yml
- package.json
- yarn.lock
> Improve GitHub actions

- .github/workflows/code-qa.yml
- .github/workflows/release.yml
- package.json
- yarn.lock
> Enforce Node 12.x

- .github/CODEOWNERS
- renovate.json
> Replace reviewers in renovate.json with CODEOWNERS file

- vercel.json
> Remove 404 configuration

- .eslintrc
- .prettierrc
- microfrontends/blog/gatsby-config.js
- microfrontends/news/gatsby-config.js
- microfrontends/profiles/gatsby-config.js
- microfrontends/webinars/gatsby-config.js
- package.json
- site/gatsby-config.js
- yarn.lock
> Use @maiertech/eslint-config and @maiertech/prettier-config

- package.json
- site/package.json
- yarn.lock
> Remove cross-env dependency

- .github/workflows/test.yml
> Rename code-qa.yml to test.yml

- .github/workflows/release.yml
- package.json
> Use personal access token to trigger workflows when changeset/action creates PR

- .github/dependabot.yml
> Switch Dependabot to weekly

- .github/dependabot.yml
> Switch Dependabot to monthly updates

- vercel.json
> Remove vercel.json

- microfrontends/blog/package.json
- microfrontends/news/package.json
- microfrontends/profiles/package.json
- microfrontends/webinars/package.json
- site/gatsby-config.js
- site/package.json
> Rename packages of micro frontends

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/extensions.json
- .vscode/settings.json
> Add .devcontainer

- .devcontainer/devcontainer.json
- .vscode/extensions.json
> Remove opinionated VS Code extensions and settings

- .devcontainer/devcontainer.json
- .vscode/extensions.json
> Update container config

- microfrontends/profiles/package.json
- microfrontends/profiles/src/@undataforum/gatsby-theme-profiles/i18n/translations/en.js
- site/package.json
- site/src/gatsby-plugin-theme-ui/index.js
> Deep merge without deepmerge package

- microfrontends/blog/src/@undataforum/gatsby-theme-blog/i18n/translations/en.js
- microfrontends/news/src/@undataforum/gatsby-theme-blog/i18n/translations/en.js
- site/src/@undataforum/gatsby-theme-blog/i18n/translations/en.js
- themes/gatsby-theme-blog/README.md
- themes/gatsby-theme-events/README.md
- themes/gatsby-theme-profiles/README.md
> Update READMEs on how to shadow localizations

- .changeset/smart-scissors-smile.md
- package.json
- packages/gatsby-theme-events/package.json
- yarn.lock
> Add missing dependency gatsby-core-utils to theme-events

- .devcontainer/devcontainer.json
> Remove version number from image prop in devcontainer.json

- examples/core-themes/static/robots.txt
- examples/undataforum/static/robots.txt
> Add robots.txt to examples to prevent indexing

- package.json
- yarn.lock
> Upgrade to @maiertech/eslint-config v0.16.0

- .changeset/rich-bags-arrive.md
- examples/core-themes/package.json
- examples/undataforum/package.json
- examples/undataforum/src/@undataforum/gatsby-theme-blog-core/components/posts-page.js
- examples/undataforum/src/@undataforum/gatsby-theme-profiles-core/components/profile-page.js
- examples/undataforum/src/@undataforum/gatsby-theme-profiles-core/components/profiles-page.js
- packages/gatsby-theme-base/package.json
- packages/gatsby-theme-base/src/components/layout.js
- packages/gatsby-theme-blog-core/package.json
- packages/gatsby-theme-events/src/components/events-page.js
- packages/gatsby-theme-profiles-core/package.json
- sites/test/src/pages/index.js
- yarn.lock
> Add support for React v17

- .huskyrc
- package.json
- yarn.lock
> Extract husky config from package.json into .huskyrc

- lint-staged.config.js
- package.json
- yarn.lock
> Improve lint-staged config

- .changeset/heavy-apples-juggle.md
- examples/core-themes/gatsby-config.js
- examples/core-themes/package.json
- examples/undataforum/content/pages/contact.mdx
- examples/undataforum/gatsby-config.js
- examples/undataforum/package.json
- package.json
- packages/gatsby-theme-base/content/pages/contact.mdx
- yarn.lock
> Remove contact page

- .changeset/loud-games-share.md
- packages/gatsby-theme-base/content/pages/copyright.mdx
> Change Copyright page description

- examples/undataforum/gatsby-config.js
> Fix config for @undataforum/gatsby-theme-base in undataforum-example

- .changeset/grumpy-shrimps-refuse.md
- packages/gatsby-theme-base/content/pages/404.mdx
> Fix path of 404 page

- .vscode/extensions.json
> Remove comment

- examples/core-themes/package.json
- examples/undataforum/package.json
- package.json
- yarn.lock
> Fix ESLint warnings in console

- examples/undataforum/content/events/event-4/multiple-paras-with-import.mdx
- examples/undataforum/gatsby-config.js
- examples/undataforum/package.json
- examples/undataforum/src/@undataforum/gatsby-theme-events-core/components/event-page.js
- yarn.lock
> Use gatsby-remark-copy-linked-files to link to files in MDX content

- examples/undataforum/content/events/event-4/multiple-paras-with-import.mdx
> Use gatsby-remark-images to embed images into MDX

- yarn.lock
> Fix failing release action
